### ISSUE TITLE
Corrección  de texto en el informe de Jefatura (Encabezado)

### ISSUE THREAD

**Issue by cechus** [MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE#346]
En atención a solicitud de fecha 16 de enero de 2018, del beneficio de Fondo de Retiro Policial, la Sra. Eusebia Aruquipa Chambi vda. De Carvajal con CI. 4836388 LP., en calidad de viuda del Sr. CBO. BERNABE CARVAJAL VALENCIA con C.I. N° 4836338 LP, solicita el beneficio del Fondo de Retiro Policial Solidario por FALLECIMIENTO y en cumplimiento al numeral 8 del artículo 45 del Reglamento de Fondo de Retiro Policial Solidario, elevo el presente informe de revisión:

**Comment by Vrian7** [comment]
corregido
