### ISSUE TITLE
Correccion de Texto en informe de jefatura (II .PROCEDIMIENTOS REALIZADOS.–)

### ISSUE THREAD

**Issue by cechus** [MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE#347]
Conforme a Dictamen Legal de la Unidad de Fondo de Retiro Policial, Cuota y Auxilio Mortuorio de la Dirección de Beneficios Económicos, mediante <b>Cite: DBE/UFRPSCAM/AL-DL N°574/2018 de fecha 28 de junio de 2018</b>

**Comment by Vrian7** [comment]
corregido
