### ISSUE TITLE
Revision de documentos Fondo de Retiro por Retiro Forzoso

### ISSUE THREAD

**Issue by Vrian7** [MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE#359]

**Comment by feliking** [comment]
Punto 3.-
En el sistema:
Fotocopia de la cédula de identidad del titular, **vigente a la fecha de solicitud.**
En el contrato:
Fotocopia de la cédula de identidad del titular.

**Comment by feliking** [comment]
Punto 5.3.-
En el sistema:
Memorándum de baja definitiva emitida por el Comando General de la Policía Boliviana (original).
En el reglamento:
Memorándum de baja definitiva emitida por el Comando General de la Policía Boliviana (original **o copia legalizada**).

**Comment by feliking** [comment]
Punto 6.2:
En el sistema:
Certificado de haberes otorgado por el comando general de la Policía Boliviana de los últimos 60 meses efectivamente percibidos, antes de su desvinculación laboral con la Institución Policial (original).
En el reglamento:
Certificado de haberes otorgado por el **C**omando **G**eneral de la Policía Boliviana de los últimos 60 meses efectivamente percibidos, antes de su desvinculación laboral con la Institución Policial (original).

**Comment by feliking** [comment]
Punto 6.3.-
En el sistema:
Certificado de haberes otorgado por el Comando general de la Policía Boliviana, de los últimos 60 meses efectivamente percibidos antes de su destino a disponibilidad de las letras(reserva activa), (original).
En el reglamento:
Certificado de haberes otorgado por el Comando **G**eneral de la Policía Boliviana, de los últimos 60 meses efectivamente percibidos antes de su destino a disponibilidad de las letras(reserva activa), (original).

**Comment by Vrian7** [comment]
se reviso y modifico exitosamente los documentos en coordinacion con la unidad
