### ISSUE TITLE
Revision de documentos Fondo de Retiro por Fallecimiento

### ISSUE THREAD

**Issue by Vrian7** [MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE#360]

**Comment by ivangrover12** [comment]
punto 2.
En el sistema
...a momento de inicio de tramite.
En el contrato
...a momento de inicio del tramite.

**Comment by ivangrover12** [comment]
punto 6
En el sistema
Memorándum de destino a disponibilidad a las letras "C" y "A" (reserva activa) según corresponda (original).
En el reglamento
Memorándum de destino a disponibilidad a las letras "C" y "A" (reserva activa) según corresponda (original o copia legalizada).

**Comment by ivangrover12** [comment]
punto 9
En el sistema
Certificado de estado civil.
En el reglamento
Certificado de descendencia del titular fallecido, emitido por el SERECI (original y actualizado).

**Comment by ivangrover12** [comment]
punto 10
En el sistema
Certificado de descendencia del titular fallecido emitido por el SERECI (original y actualizado).
En el reglamento
Declaratoria de herederos (original o copia legalizada), en el caso de herederos por sucesión testamentaria presentar "Testamento", dentro del cual señale expresamente la otorgación del beneficio (Original o copia legalizada)

**Comment by Vrian7** [comment]
se reviso y modifico exitosamente los documentos en coordinacion con la unidad
