### ISSUE TITLE
Revision de documentos Fondo de Retiro por Retiro Voluntario

### ISSUE THREAD

**Issue by Vrian7** [MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE#362]

**Comment by feliking** [comment]
Punto 3.-
En el sistema:
Fotocopia simple de cédula de identidad del titular, **vigente a la fecha de solicitud.**
En el reglamento:
Fotocopia simple de cédula de identidad del titular.

**Comment by feliking** [comment]
Punto 5.1.-
En el sistema:
Resolución de baja definitiva a solicitud voluntaria, emitida por el Comando General de la Policía Boliviana (original).
En el reglamento:
Resolución de baja definitiva a solicitud voluntaria, emitida por el Comando General de la Policía Boliviana (original **o copia legalizada**).

**Comment by feliking** [comment]
Punto 5.2.-
En el sistema:
Memorándum de baja definitiva a solicitud voluntaria, emitida por el Comando General de la Policía Boliviana (original).
En el reglamento:
Memorándum de baja definitiva a solicitud voluntaria, emitida por el Comando General de la Policía Boliviana (original **o copia legalizada**).

**Comment by Vrian7** [comment]
se reviso y modifico exitosamente los documentos en coordinacion con la unidad
