### ISSUE TITLE
Revision de documentos Fondo de Retiro por juvilacion

### ISSUE THREAD

**Issue by Vrian7** [MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE#363]

**Comment by ivangrover12** [comment]
punto 2.
En el sistema
_...a momento de inicio de tramite._
En el contrato
_...a momento de inicio del tramite._

**Comment by ivangrover12** [comment]
punto 5
En el sistema
...(original).....
En el reglamento
...(original o copia legalizada).....

**Comment by ivangrover12** [comment]
punto 7
En el sistema
Certificado de haberes otorgado por el Comando general de la Policía Boliviana, de los últimos 60 meses efectivamente percibidos antes de su destino a disponibilidad de las letras(reserva activa), (original).
En el reglamento
Certificado de haberes otorgado por el Comando General de la Policía Boliviana, considerando los últimos 60 meses, antes de su ingreso a la disponibilidad (reserva activa), hasta el ultimo aporte efectivizado (original).

**Comment by Vrian7** [comment]
documentos revisados y corregidos
